### ISSUE TITLE
Coin Stream Set

### ISSUE THREAD

**Issue by shachoi** [showlab/videollm-online#18]
Hi @chenjoya, 
First of all, thank you for your prompt response and support!!

I’m also looking to train using the Coin dataset. Currently, the only released Coin-related resource is for its benchmark, correct?
Could you release the Coin stream set, which generates online dialogue from COIN offline annotations?

**Comment by shachoi** [comment]
Thanks for the response!

**Comment by yankee624** [comment]
@chenjoya According to section 3.2 in paper (and also the [code](https://github.com/showlab/videollm-online/tree/main/data/livechat)), the "Offline Annotations to Video Streaming Dialogue" is done by inserting multiple queries randomly in the video. But in Supplementary B.1 and B.2 COIN Stream Example, only single query is inserted in the beginning. Can you provide code/explanation on how this single query dataset is generated? Is it just using a single fixed template `The video is about to [action description]. Please remind me when the related action starts, summarizes when it ends, as well as forecasts the next action.` for all videos?

**Comment by chenjoya** [comment]
Ok seems you asked the COIN stream set. It is very simple, 

1. Video: COIN video (no segment);
2. Prompt: [action description] = COIN task label
3. Annotated Response: (1) After the frame of a step label begins, make the prompt "The action of {steps[i]} starts." (2) After the frame of a step label ends, make the prompt "The action of {steps[i]} ends. The next is {steps[i+1]}".

As you see, it is not using LLM, just rule-based. Livechat generation is more recommended.

**Comment by yankee624** [comment]
@chenjoya Thank you for the prompt reply!
Livechat is good for better-quality response, but as you said in the paper, multi-turn dialogue is hard to evaluate, so I was wondering how to generate the COIN stream set.

- For the initial prompt (user query), did you just use the raw task label (e.g., "InstallCeilingFan")? Or did you use some kind of template like `The video is about to install ceiling fan. Please remind me when the related action starts, summarizes when it ends, as well as forecasts the next action.` as shown in the paper. 

- Do you think training and evaluating the model only with this COIN Stream set will be unreliable? (maybe the metrics are unreliable because the dataset is too fixed structure?)

**Comment by chenjoya** [comment]
Hi thank you!

- Yes, the task label has been split by https://github.com/showlab/videollm-online/blob/755e2652a651ae2e43bb2f9d28281a2540a3bbac/data/coin/coin.py#L54

- If using only the COIN Stream set, the data size is too small. Mixed training is recommended.

**Comment by yankee624** [comment]
Do you mean that the user query is just "Install ceiling fan"? 
Then it would go as follows?
```
[System prompt]
User: Install ceiling fan
[F][F]...[F] Assistant: xxx
[F][F]...[F] Assistant: xxx
```


This is different from the example in the paper, which includes some sentences in the user query ("The video is about to..."). Is this example just for demonstratation purpose, not the real example?
<img width="489" alt="image" src="https://github.com/user-attachments/assets/22d0328d-be6a-4374-b737-37982d4bf511">

**Comment by chenjoya** [comment]
Sorry for the confusion. What I mentioned is the code to split task label. The prompt in paper is correct.

**Comment by yankee624** [comment]
Thank you!
