### ISSUE TITLE
Evaluation on COIN

### ISSUE THREAD

**Issue by pha-nguyen** [showlab/videollm-online#2]
Hi, thank you for the great work!
Could you please disclose the scripts for COIN will be released anytime soon?

**Comment by chenjoya** [comment]
Hi, thank you! They will be released in several hours.

**Comment by chenjoya** [comment]
Now I close this issue. Please reopen it once you have any problems.

**Comment by chenjoya** [comment]
Hi, please dont do that. 128256 is just a placeholder, it will be replaced with image embedding during forwarding.

**Comment by chenjoya** [comment]
Could you give me the full scripts that you run? Thank you so much.

**Comment by chenjoya** [comment]
Thank you. I will check that. After 3pm today.

**Comment by chenjoya** [comment]
Hello, I cannot reimplement your problem by training COIN. 

```input_ids is out of range of config.vocab_size.```

This is okay, since we just use 128256 as a placeholder, it will not call get_inputs_embeddings. Its weird the program will call this line:

<img width="686" alt="image" src="https://github.com/showlab/videollm-online/assets/20626415/1981dc16-7448-4ade-a3f8-21ab18234ea2">

This should only be called when we do not have visual frames (only language tokens). In this situation, the input_ids should not have 128256, since there is no frames need to use placeholder.

Could you provide me the full scripts? So I can debug with that. Thank you!

**Comment by shachoi** [comment]
Hi @chenjoya 
First, thank you for your prompt response and support!!

I’m also looking to train using the COIN dataset. Currently, the only released COIN-related resource is for the COIN benchmark, correct?
Could you release the Coin stream set, which generates online dialogue from COIN offline annotations?

**Comment by chenjoya** [comment]
I am so sorry that the COIN evaluation indeed exists some bugs. So sorry for that. Now they have been fixed. The main changes are 

1. Add a generation_after_embed func 

https://github.com/showlab/videollm-online/blob/c07b1133eaa63e352f4e1cea8217d13088f2416f/data/coin/benchmarks.py#L10

https://github.com/showlab/videollm-online/blob/c07b1133eaa63e352f4e1cea8217d13088f2416f/models/live_llama/modeling_live_llama.py#L69-L70

2. During evaluation, do not provide assistant responses

https://github.com/showlab/videollm-online/blob/c07b1133eaa63e352f4e1cea8217d13088f2416f/data/coin/benchmarks.py#L27-L28

Hope the above helps!
